### ISSUE TITLE
CreateFormGroupArgs not exported

### ISSUE THREAD

**Issue by dhilgarth** [telerik/kendo-angular#2121]
**Describe the bug**
`import { CreateFormGroupArgs } from '@progress/kendo-angular-scheduler';` is not working, because that type has not been exported.
Instead, I have to resort to this:
```
import {CreateFormGroupArgs} from '@progress/kendo-angular-scheduler/dist/es2015/editing-directives/create-form-group-args.interface';
```

**Expected behavior**
It should work - the documentation even says it should work: https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/

**Additional context**
I am using the latest dev version: 0.10.0-dev.201903080807

**Comment by ipeshev** [comment]
Fix available in [latest dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fix released in 0.10.0

**Comment by xinthose** [comment]
Issue still exists.

**Comment by Raisolution** [comment]
@xinthose Yes 👍

**Comment by xinthose** [comment]
@Raisolution OK.  Well, I was still having problems for some reason.

**Comment by tsvetomir** [comment]
Please, check that you're using v0.11.0:

`npm ls @progress/kendo-angular-scheduler`

It might be necessary clean-up lock files and reinstall to get the latest version:

```
rm -rf node_modules package-lock.json
npm install
```
