### ISSUE TITLE
[Grid] Focusing the header when virtualization and navigable are true causes scroll to top

### ISSUE THREAD

**Issue by bundyo** [telerik/kendo-angular#3171]
When you add to a grid virtual scrolling and navigation, clicking on the header will scroll the grid to top. This is especially visible if there is a filter menu in the header - it will scroll on menu open.

**To Reproduce**
The issue is reprodicable in the demos:
https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-virtualization-with-local-data

Also check this Stackblitz:
https://stackblitz.com/edit/angular-bymamz-uxfb9x?file=app/app.component.ts

**Expected behavior**
To not scroll on header click

**Browser**
 - OS: All
 - Browser: tested in Firefox and Chrome, probably all
 - Version: latest

**Comment by tsvetomir** [comment]
Fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Shipped in v5.0.1

**Comment by RajagurunathanManikandan** [comment]
Hai @tsvetomir @yanmariomenev, 

I recently raised a support ticket for Grid auto-scroll functionality. To know more about the ticket [click here](https://www.telerik.com/account/support-tickets/view-ticket/1526019).

After applying the suggested solution from the ticket. I'm facing this bug. Any workaround solution for this bug? 
Because we're using "@progress/kendo-angular-grid": "^4.8.4". Since the development is dependent on this, kindly share the workaround solution if any.  

Thanks,
Rajagurunathan

**Comment by yanmariomenev** [comment]
Hi Rajagurunathan,

Your question will be answered in our support ticket conversation.

I hope you have a nice day.

Regards,
Yanmario Menev

**Comment by RajagurunathanManikandan** [comment]
Hi @tsvetomir @bundyo  @yanmariomenev 
This issue is still happening in Grid V.5.2.1.
Here is the [stackblitz example](https://stackblitz.com/edit/grid-navigable-scrolltop-issue?file=app/app.component.ts).

**Comment by tsvetomir** [comment]
@RajagurunathanManikandan the [rowHeight]() is not set in this example which leads to incorrect scroll calculations.
It should be set to 42px to match the styling, see [updated example](https://stackblitz.com/edit/grid-navigable-scrolltop-issue-ph2apj?file=app%2Fapp.component.ts).
