### ISSUE TITLE
[Editor] Toolbar Gradient ColorPicker closes it's popup on interaction

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3678]
**Describe the bug**
The Editor Toolbar ColorPicker with set view "gradient" closes the popup upon interaction. The first time the popup is open it seems the component works as expected allowing the user to interact with the colors and sliders. However, the second time the popup is opened then it closes automatically when the user selects or interacts with the slider. In some cases, the first interaction with the ColorPicker closes the popup.

**To Reproduce**
1. Open our Toolbar tools example and interact with the background ColorPicker - https://stackblitz.com/edit/angular-9eurxd?file=src%2Fapp%2Fapp.component.ts

Screen recording:
https://user-images.githubusercontent.com/49076727/169748791-c81fde89-97f9-45f7-b210-a8610dc4882f.mp4

**Comment by yanmariomenev** [comment]
Update ticket **1565991** when the fix is available.

**Comment by chakshutadesai** [comment]
I am facing the same issue, Very critical

**Comment by meriturva** [comment]
Update ticket 1568388 also!

**Comment by meriturva** [comment]
Please reopen the issue.....still present in case multiple views are used:

Work:
`<kendo-toolbar-colorpicker kendoEditorForeColor [views]="['gradient', 'palette']" [paletteSettings]="{ palette: 'basic'}"></kendo-toolbar-colorpicker>`

Don't work again:
`<kendo-toolbar-colorpicker kendoEditorForeColor [views]="['palette', 'gradient']" [paletteSettings]="{ palette: 'basic'}"></kendo-toolbar-colorpicker>`

Thanks.
