### ISSUE TITLE
[Gantt] Timeline header styling and colspan issue

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3832]
**Describe the bug**
When the Gantt component is loaded in a locale other than en-US, the week view's timeline header has a styling issue and the month view's timeline header does not apply the expected colspan value to the td element.

**To Reproduce**
[StackBlitz example](https://stackblitz.com/edit/angular-bjpgml?file=src/app/app.component.ts): Change the timeline's view to week and month.

**Expected behavior**
Styling and colspan value should be correctly applied for all the locales.

**Screenshots**
Week view:
![image](https://user-images.githubusercontent.com/25337886/197906118-d6c1580e-1a73-4a92-bc38-d403eb0b0263.png)

Month view:
![image](https://user-images.githubusercontent.com/25337886/197906204-3f220463-03bc-4cc2-85a4-cd8e131f9a83.png)

**Comment by snyappy** [comment]
Can still reproduce this in 12.0.0: 
[https://stackblitz.com/edit/angular-swxdbg?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-swxdbg?file=src%2Fapp%2Fapp.module.ts)
https://www.telerik.com/kendo-angular-ui/components/gantt/globalization/

Can we expect a fix for this soon? This issue has been open for 6 monhts

**Comment by svetq** [comment]
@snyappy the issue is reproducible only in StackBlitz. We are unable to reproduce it in a local project. Please provide a local project as an archive where the issue can be observed.

**Comment by snyappy** [comment]
[angular.zip](https://github.com/telerik/kendo-angular/files/12816564/angular.zip)

Not quite sure how to share this? I simply built the stackblitz project, installed node packages and started the project with ng serve, no other changes. 

could reproduce the issue immediately when switching from day to month view.

**Comment by svetq** [comment]
@snyappy 
[gantt-test.zip](https://github.com/telerik/kendo-angular/files/12844081/gantt-test.zip)

I did see that the issue is reproducible using Angular 13 in the provided project. Thank you. But using Angular v 16 doesn't yield this issue. It looks like there was some issue in Angular that was affecting the Gantt and is now fixed. Please see the same project as yours but with Angular 16 attached. I would advise updating the Angular project as v 13 is no longer supported: https://angular.io/guide/releases#actively-supported-versions

**Comment by snyappy** [comment]
@svetq Hi, in your project you missed providing a different locale in app.module (For example finish like in the original issue or in my case german) 

Inside app.module:

import '@progress/kendo-angular-intl/locales/de/all';

providers: [{ provide: LOCALE_ID, useValue: 'de' }],

I can still reproduce this error in your project with Angular16.

**Comment by snyappy** [comment]
@svetq Since this issue was reopened: Were you able to reproduce the behaviour now?

**Comment by svetq** [comment]
@snyappy Yes, we are able to reproduce the issue. Thank you.

**Comment by svetq** [comment]
@snyappy I am no longer able to reproduce the issue using the latest version 14.1.0. Could you please check and confirm?

**Comment by snyappy** [comment]
@svetq Yes, 14.1.0 fixed this.

https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v14.1.0 
gantt: incorrect timeline slot calculations with different locales

Thanks for your support!
