### ISSUE TITLE
NPM issue - @progress/kendo-angular-dropdowns  now only has the version version 0.1.0

### ISSUE THREAD

**Issue by masterjs** [telerik/kendo-angular#682]
Hello,
Our entire build process now stopped working because the @progress/kendo-angular-dropdowns versions are no longer available. The command `npm view @progress/kendo-angular-dropdowns versions --json` is now only returning the version 0.1.0 compared to multiple in the past (like 1.0.10). 

Anything can be done on your side to fix this (really soon..)?

thank you,
JS

**Comment by abhissha** [comment]
We run into the same issue with only version 0.1.0 showing on the kendo repository.

**Comment by tsvetomir** [comment]
The issue should be fixed now, apologies for the inconvenience.

**Comment by masterjs** [comment]
I confirm that its now working, thank you for the fast response, really appreciated.

JS

**Comment by masterjs** [comment]
Ok, spoke too soon, now they are in fact available, but I keep on getting integrity issues now:

npm ERR! shasum check failed for C:\Users\SVC-TF~2\AppData\Local\Temp\npm-26016-5e341f22\registry.npm.telerik.com\_40progress_252fkendo-angular-dropdowns\-\kendo-angular-dropdowns-1.0.10.tgz
npm ERR! Expected: 54fa32b72bead69eae4d16a6af30837565214e27
npm ERR! Actual:   af13cb751e62e1bf35621c4f8c4d2fdf7d07ab49
npm ERR! From:     https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns/-/kendo-angular-dropdowns-1.0.10.tgz

Is there still an issue on your side?

JS

**Comment by tsvetomir** [comment]
We had to republish the affected versions and the SHAs will be different. You'll need to delete your `package-lock.json` file if you're using npm 5. Sorry!

**Comment by masterjs** [comment]
Hello @tsvetomir ,
I do not keep `package-lock.json` on the build server and it runs on npm 4.2. Know any other way around this issue or are you sure the the repository publishes the right sha?

**Comment by talynone** [comment]
Same issues, I updated to npm5 from npm3 and didn't help. Now get this error : 
`npm ERR! code EINTEGRITY
npm ERR! sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= integrity checksum failed when using sha1: wanted sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= but got sha1-6NZO/nltbKXAhb/ugnirSiPoB0A=. (141963 bytes)`

**Comment by amartinelli6577** [comment]
Same issues here as well. shasum check keeps failing. I've tried this with npm versions 5.0.3, 4.6.1, and 3.10.10.

**Comment by masterjs** [comment]
I also just for the fun tried 
`"@progress/kendo-angular-dropdowns": "http://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns/-/kendo-angular-dropdowns-1.0.11.tgz"` 
in my package.json, but this times-out... so no luck there.  :o(

JS

**Comment by tsvetomir** [comment]
We released an updated version that should not have the checksum issue. To get it run:

`npm install --save @progress/kendo-angular-dropdowns@^1.1.0`

Older versions are not yet restored, we'll continue that effort. Sorry everyone!

**Comment by masterjs** [comment]
Hello @tsvetomir, 
Thank you. I'm confirming that the full process is now working with v 1.1.0.

JS

**Comment by Quovadisqc** [comment]
Hi @tsvetomir

Is there any ETA on when the @ng2 packages will be fixed?

Thanks!

**Comment by tsvetomir** [comment]
@Quovadisqc @whuang02  please try downloading the package again. Apologies.

**Comment by whuang02** [comment]
Hi @tsvetomir, 

I'm still getting a 404 for the @telerik/kendo-dropdowns-common package.
When I go to:  [](http://registry.npmjs.org/@telerik%2fkendo-dropdowns-common), I also see a 404 Not Found.

**Comment by tsvetomir** [comment]
The @telerik/kendo-dropdowns-common package is hosted on http://npmjs.org and shouldn't be affected by this outage. Try running `npm cache clean`  and `npm install` to see if it isn't a cache issue.

**Comment by whuang02** [comment]
Cleaning the cache doesn't fix the issue.

I'm able to download regular packages from npmjs.org, but it seems that all scoped packages are giving me a 404.

I thought it was an issue with scoped packages, but strangely, I'm able to download scoped packages from registry.npmjs.telerik.org

**Comment by tsvetomir** [comment]
How about other scoped packages from npmjs.org such as [@angular/core](https://www.npmjs.com/package/@angular/core) and [@telerik/semantic-prerelease](https://www.npmjs.com/package/@telerik/semantic-prerelease)?

**Comment by masterjs** [comment]
@whuang02 is it possible that you have caching issues? I just did http://registry.npmjs.org/@telerik%2fkendo-dropdowns-common and I got a HTTP 200

**Comment by whuang02** [comment]
@tsvetomir other scoped packages even @angular/core, common, etc are failing 
@masterjs I've tried cleaning the cache and removing node_modules no luck with that.

Is there anyway I can just manually install the @telerik/kendo-dropdowns-common, so I can download the @progress/kendo-angular-dropdowns module?

It's able to properly resolve the @progress/kendo-angular-dropdowns module, but fails once it reaches the dependency.

**Comment by masterjs** [comment]
@whuang02 you could "maybe" try `https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns/-/kendo-angular-dropdowns-1.0.10.tgz` and replace the tarball with the expected version. That is something that is not working on my build server for unknown reason, but locally its ok.

**Comment by tsvetomir** [comment]
@masterjs try deleting the _node_modules_ folder and running `npm cache clean` for good measure.

**Comment by masterjs** [comment]
@tsvetomir I believe you meant @whuang02    ;o)

**Comment by whuang02** [comment]
@masterjs 

Thanks I'm able to manually install the dependencies using the tarbell URLs.
I can now install the dropdown module thanks.  

I think the 404 issue is caused by the '/' encoding not working properly.

It's hitting '**https://registry.npmjs.org/@telerik/kendo-dropdowns-common**' rather than '**https://registry.npmjs.org/@telerik/kendo-dropdowns-common**'

**Comment by whuang02** [comment]
Found out this issue was caused by OpenDNS redirections... The '%2f' gets resolved into a '/' during redirection.

**Comment by tbrookin** [comment]
I've been having these same errors (Sha mismatches).  Now I'm getting "Unregistered users are not allowed to access package @progress kendo-angular-inputs".  I can't build.  And I can't deploy any fixes to my production product.

**Comment by tbrookin** [comment]
Not sure what I did, but this (npm auth) is working now.
