### ISSUE TITLE
Scroll alternates only between two months

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#685]
It can be reproduced on [official demo]( http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/) try to open calendar and to scroll down, it alternated only between April 2000 - March 2000.

**Comment by EricSch** [comment]
Probably the same issue I had once with #439 . 
The problem is in the two way binding, without the two way bindings it scrolls smoothly.
Could it be, that the variable 'value' is set with a new instance of a Date?

**Comment by mr-alede** [comment]
Thanks for proposing a workaround. I am trying to follow what was proposed in [#439](https://github.com/telerik/kendo-angular/issues/439) but unfortunately it doesn't work for me.

Here is what my Datepicker encapsulation component looks like:
```javascript
<kendo-datepicker #datepicker (valueChange)="setValue($event)">
</kendo-datepicker>
```

```javascript
import { Component, OnInit, HostBinding, Input, Output, EventEmitter, ViewChild } from '@angular/core';
import { DatePickerComponent } from "@progress/kendo-angular-dateinputs";

@Component({
  selector: 'app-datepicker',
  templateUrl: './datepicker.component.html',
  styleUrls: ['./datepicker.component.scss']
})
export class DatepickerComponent implements OnInit {
  @ViewChild('datepicker') _datepicker: DatePickerComponent;
  _model: Date;

  @Input()
  get model() {
    return this._model;
  }

  @Output() modelChange = new EventEmitter();
  set model(val) {
    if (val !== this._model) {
      this._model = val;
      this.modelChange.emit(this._model);
      this._datepicker.writeValue(val);
    }
  }

  constructor() { }

  ngOnInit() {
  }

  setValue(value: Date) {
    this.model = value;
  }

}
```

Could you guys give me a hint what's wrong in my component? I don't use any Angular binding at all to interact with Kendo DatePicker. And the problem still exists.

**Comment by EricSch** [comment]
I didn't test it, but try to omit the ` this._datepicker.writeValue(val);` The datepicker should already have the right value.

**Comment by mr-alede** [comment]
:) With that line commented out the datepicker behaves the same. I just
loose any ability to set the picker value programmatically. Moreover, even
if I leave following in the component template:
<kendo-datepicker></kendo-datepicker> I see the same anyway. It looks like
all we can do is to wait for this issue to be resolved. As a temporal
solution I use DatePicker from Kendo for jQuery framework.

On Wed, Jun 28, 2017 at 9:19 AM, Eric Schoenholzer <notifications@github.com

**Comment by EricSch** [comment]
@mr-alede ok, seems so, we have to wait. But it is also true, that the value is already set, when (valueChange) is called. So it is obsolete to set the value again.

I don't know was has changed internally since my issue #439, but the behavior was the same. Let see what Telerik says :pray:

**Comment by ggkrustev** [comment]
Hi guys, thanks for the additional details shared in this thread.

Our investigation so far showed that the issue is reproducible only in Chrome (tested also in Firefox and Safari). The browser will scroll the list automatically when the first <TBODY> element is removed (auto-scroll persistence feature), which messes up our virtualization logic quite a bit.

Basically, when user scrolls, our virtualization component listens to the scroll position and updates the list of months to provide the desired feeling of "infinite months list". When table content is updated, the list is auto-scrolled to a bigger scroll position, which triggers the virtualization logic, and reverts the page to the previous one. This causes this 2 months scroll loop.

We will continue working on this issue and will update the thread once we have a fix.

**Comment by ggkrustev** [comment]
Quick update:
We pushed a fix in the latest DEV release (v1.0.6-dev.201706301617). It seems that the change addresses the issue on our end, but it will be great if someone in different environment too.

**Comment by tsvetomir** [comment]
Run `npm install --save @progress/kendo-angular-dateinputs@dev` to get the development build.

**Comment by mr-alede** [comment]
You guys seem to have forgotten to publish that package. Here is what I see
in npm registry:
[image: Inline image 1]

As you can see, there's no 1.0.6-dev registered.

**Comment by tsvetomir** [comment]
See #712

**Comment by mr-alede** [comment]
Many thanks. 
I installed and tested Datepicker and can confirm that scrolling through months seems to work fine in my project. But scrolling through years doesn't seem to work properly.
![image](https://user-images.githubusercontent.com/13642761/27790566-aa020476-5ff9-11e7-8fe0-3912065ec9f9.png)
I marked in green the part which works fine now, but I still have problems when scrolling in the part marked in red. Sometimes year is changed correctly, sometimes not.

**Comment by ggkrustev** [comment]
Hi @mr-alede,
I tried to replicate the issue on our DEV staging, but to no avail. Could you review the screencast of my test and let me know if I am missing something?

https://www.screencast.com/t/BctbdFcxxz

The test browser is Chrome.

**Comment by mr-alede** [comment]
Hi.

It works perfectly in your screencast. Maybe I am doing something wrong in
my project. I will try to leave the picker without any Angular bindings.

**Comment by mr-alede** [comment]
Here is how Datepicker works in my project:
[Demo](https://drive.google.com/file/d/0Bzka6pAeQ8KEdnRTOUYyN2FZOHM/view).

I intentionally removed any Angular bindings from Datepicker instance, and I still have problems with the part on the left. The video demonstrates "@progress/kendo-angular-dateinputs@1.0.6-dev.201706301617" in Chrome.  Actually, that is not a big problem as I have Kendo for jQuery Datepicker integrated in my project as a fallback.

**Comment by ggkrustev** [comment]
Yeah, it looks quite broken :(.
Would it be possible to replicate the issue in a standalone plunkr or in ng-cli generated demo? Anything that would allow us to observe the issue locally would be great help! It will be really hard to continue with the investigation based on the provided screencast.

**Comment by ggkrustev** [comment]
@mr-alede, on a second thought, the issue seems to be heavy related to used CSS. Probably it issue will be replicated easily using the CSS from the project page. Could you try to build a Plunkr with that info?

As a side note, you can open a support, thread sharing more details about the current project. We could even arrange a remote session to investigate the issue on your side.

**Comment by mr-alede** [comment]
Probably arranging a remote session would be the easiest way for me. What
software should I install on my machine for you to be able to work remotely
on my comp? Is it possible to arrange a session today?

**Comment by ggkrustev** [comment]
I do believe that it will be possible for today, as we have an available remote session slot. As to how to request a remote session, check the following guideline:

https://www.telerik.com/account/remote-web-assistance

Please note that the support service entitled to your license should include the option for remote sessions. If this is not the case, then we will need to request a repro demo to work with.

**Comment by mr-alede** [comment]
Created ticket 1117754  Waiting for an answer. Not sure if my license
allows Remote assistance, though.
