### ISSUE TITLE
Wrong output when typing in dateinput

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#686]
It can be reproduced in [official demo](http://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/) with default format MM/dd/yyyy

type 02022016 -> 2/22/0016
type 91216 -> 9/12/0016 which is kind of expected since we do not make assumption about the millenium
type 34 as day -> it is transformed to 4 without error indication

**Comment by ggkrustev** [comment]
All described issues are caused by the insufficient auto-switching of the date segments. Basically, we do not move to the next segment all the time, which will cause the final input incorrect.

Although the behavior is expected, it is far from perfect. We will update the thread once we improve the behavior of the DateInput component.

**Comment by eatinasandwich** [comment]
Is this something that is going to be fixed anytime in the near future or will it be a while?

**Comment by ggkrustev** [comment]
Hi @eatinasandwich,
the reported issue is in our TODO list and we will fix it in some of our next releases. I am afraid that I cannot provide specific time frame when this will happen.

I would like to ask you to cast your vote for the following enhancement, which will help to increase the enhancement priority.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/31013683-allow-day-and-month-to-start-with-0-when-manually

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by eatinasandwich** [comment]
Forgive me for being a bit naive, but I've never tested a dev version of a package before. Is it just 
`npm install @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730`

If so that's showing "invalid" at the end of the package name after install. Is there a dependent package that I need to update as well? 

Thanks for the update!

**Comment by ggkrustev** [comment]
Hi @eatinasandwich,
the easiest way to install the dev package is just to use `@dev` tag. Just run:
```
npm i @progress/kendo-angular-dateinputs@dev
```
You can also update all internal dependencies using `npm --depth 2 update` ([docs](https://docs.npmjs.com/cli/update#description)).

Verify that the `dev` version is installed running this command:
```
npm ls @progress/kendo-angular-dateinputs
```

The output should be `@progress/kendo-angular-dateinputs@1.4.0-dev.201711011505`

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.

**Comment by eatinasandwich** [comment]
Hi @ggkrustev 
Fix looks good for the most part, but now I'm experiencing another issue since the update. I had code previously that used the setValue function of AbstractControl. Since updating the kendo package, after calling this function the value updates on the control but the UI still shows the old value. After the control is focused (by clicking or tabbing to it) the new value is shown.

**Comment by ggkrustev** [comment]
Hi @eatinasandwich, thanks for the report.
Could you open a separate Github issue providing a repro demo? This will help us to understand the specific implementation and find the cause much faster. Thanks in advance.

**Comment by eatinasandwich** [comment]
Was able to create a minimal repro and created issue here: #1079
