### ISSUE TITLE
DatePicker - ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by dassjosh** [telerik/kendo-angular#687]
When using the DatePicker if it is close to the bottom of the screen and opens the Popup above the control it will throw the ExpressionChangedAfterItHasBeenCheckedError. If it opens below the control no error will be thrown.

Here is a slightly modified plunker to help show this: [Modified](http://plnkr.co/edit/VampTmGBKytiFjC1tONF?p=preview)      [Original](http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/) 
In this plunker I added a field called distance. Adjust this field to get DatePicker close to the bottom so it's popup will open above the control.

Steps to Reproduce:
1. Adjust the distance field value to get control near the bottom so the popup opens above the control.
2. Open the console
3. Click on the Calendar Icon
4. Error will Appear

Expected Result:
If the popup opens above the control no error should appear

Actual Result:
Error appears if popup opens above the control

**Comment by martindevos** [comment]
I am having the same problem.  No solution yet ?

**Comment by ggkrustev** [comment]
We're investigating the issue and will update the thread soon.

**Comment by aerlijman** [comment]
Same problem here.

**Comment by Sabio-JeffJ** [comment]
Same Issue here as well.  In addition, the control does not display the dates the same way as in the demo and I cannot change the value property when selecting a date. 
![datepickerissue](https://user-images.githubusercontent.com/10082903/27704145-71b3b22e-5cbe-11e7-8d41-3d29f68007fd.png)

**Comment by ggkrustev** [comment]
Hi guys,
we fixed the issue locally and soon will release a dev package. I will update the thread with more details soon.

**Comment by ggkrustev** [comment]
To all interested, the latest DEV release includes the fix. The specific version is `v1.0.6-dev.201706300648`.

**Comment by tsvetomir** [comment]
Run `npm install --save @progress/kendo-angular-dateinputs@dev` to get the development build.

Please review issue #712 as well.

**Comment by Sabio-JeffJ** [comment]
I'm curious to know if this is working for others.  I'm still having the same problem even after running the latest install mentioned by tsvetomir.

**Comment by tsvetomir** [comment]
@Sabio-JeffJ please make sure you follow the instructions in #712

**Comment by nicholasblexrud** [comment]
@tsvetomir I tried running `npm install --save @progress/kendo-angular-dateinput@dev`, but getting an error saying that `@progress/kendo-angular-dateinput` is not in the npm registry. I took a look at #712 and we are not using a .npmrc file. Thoughts on next steps? Thanks

**Comment by ggkrustev** [comment]
@nicholasblexrud the name of the package is `@progress/kendo-angular-dateinputs` (notice the plural of the input). With that change you should be able to install the package.

**Comment by nicholasblexrud** [comment]
@ggkrustev, I'm seeing error when I use datepicker. 

package.json
`    "@progress/kendo-angular-dateinputs": "^1.0.5-dev.201706261326",`

![date-input-error](https://user-images.githubusercontent.com/5520610/29045303-c1d905f4-7b88-11e7-8cae-ed65650fbde0.PNG)

**Comment by ggkrustev** [comment]
The 1.0.5 version still exposes the erroneous behavior. You will need to use dev version of 1.0.6, more specifically 1.0.6-dev.201707071314. I do believe that your npm still points to the private registry.

Please verify that you're using NPMJS registry and your cache is cleaned.

**Comment by nicholasblexrud** [comment]
@ggkrustev thank you sir - we're error free!

**Comment by bhaidar** [comment]
When is this going to be released?

**Comment by ggkrustev** [comment]
@bhaidar, the fix was just release. Check `@progress/kendo-angular-dateinputs@1.0.6`.

**Comment by ggkrustev** [comment]
Will close the thread for now. Please comment if the issue is still present in the `1.0.6` release.

**Comment by bhaidar** [comment]
Seems to be working fine now. Thanks

**Comment by ggkrustev** [comment]
If there is a problem on the second PC, then clearly issue is related to the development environment of that machine. Please examine the configuration of the environment and make sure that is configured correctly. If the problematic machine is setup correctly, then the installation should work just fine.

The Kendo UI for Angular is available from the public NPMJS, which means that developer should be able to install as any other regular NPM package.

**Comment by Milan03** [comment]
I am also getting `npm ERR! code ETARGET
npm ERR! notarget No compatible version found: @progress/kendo-angular-dateinputs@1.0.6` when I try for version @1.6.0. Also tried the `dev` version above and got the same result. Need this fix...

**Comment by joe307bad** [comment]
I am getting the same issue as @bhaidar, i am getting the following error when trying to install 1.0.6:
```
npm ERR! notarget No matching version found for @progress/kendo-angular-dateinputs@1.0.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by bhaidar** [comment]
I stopped using this control and switched to another. I hope I could help
more here.

**Comment by joe307bad** [comment]
Sorry, my issue was still using the Progress NPM registry. I removed the two lines which contain registry.npm.telerik.com from your .npmrc file which was located in my C:/Users/UserName folder.
