### ISSUE TITLE
Running an 'ng build' raises multiple "export <some-object>was not found in @progress<some-module>" warnings

### ISSUE THREAD

**Issue by simonneedham** [telerik/kendo-angular#880]
## I'm submitting a...
* Regression report 

## Current behavior
When running `ng build`, the angular cli is reporting multiple "`export <some-object>was not found in @progress<some-module>`" warnings. See bottom of the issue for the full Angular CLI response.

## Expected behavior
Angular cli doesn't report warnings about @progress modules

## Minimal reproduction of the problem with instructions
1. Update environment to current
- Angular CLI: 1.3.2
- Angular Compiler: 4.3.6
- Build an app using `@progress/kendo-angular-dropdowns` and/or `@progress/kendo-angular-dateinputs`

## What is the motivation or use case for changing the behavior?
The warnings are verbose.

## Environment

Package versions:
```
+-- @angular/animations@4.3.4
| `-- tslib@1.7.1
+-- @angular/cli@1.3.2
+-- @angular/common@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/compiler@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/core@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/forms@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/http@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/platform-browser@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/platform-browser-dynamic@4.3.4
| `-- tslib@1.7.1 deduped
+-- @angular/router@4.3.4
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-charts@1.2.3
+-- @progress/kendo-angular-dateinputs@1.0.6
| +-- @progress/kendo-angular-popup@1.1.1
| +-- @progress/kendo-date-math@1.0.3
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-angular-dialog@1.1.0
+-- @progress/kendo-angular-dropdowns@1.1.3
| +-- @progress/kendo-angular-popup@1.1.1
| +-- @progress/kendo-angular-resize-sensor@1.0.4 deduped
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-angular-excel-export@1.0.3
| +-- @progress/kendo-file-saver@1.0.1
| `-- @progress/kendo-ooxml@1.0.0
+-- @progress/kendo-angular-grid@1.3.2
| +-- @progress/kendo-angular-pdf-export@1.0.0
| +-- @progress/kendo-angular-resize-sensor@1.0.4 deduped
| +-- @progress/kendo-file-saver@1.0.1
| +-- @telerik/kendo-draggable@1.5.1
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-angular-inputs@1.1.0
| +-- @progress/kendo-angular-resize-sensor@1.0.4 deduped
| +-- @telerik/kendo-draggable@1.5.1 deduped
| +-- @telerik/kendo-inputs-common@2.2.2
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-angular-intl@1.2.2
+-- @progress/kendo-angular-l10n@1.0.3
+-- @progress/kendo-angular-layout@1.0.5
+-- @progress/kendo-data-query@1.0.6
| `-- tslib@1.7.1 deduped
+-- @progress/kendo-drawing@1.2.0
| `-- pako@1.0.5
+-- @progress/kendo-theme-default@2.40.0
+-- @progress/kendo-ui@2017.2.621
| `-- jquery@3.2.1 deduped
+-- @telerik/kendo-intl@1.2.0
+-- @types/geojson@1.0.2
+-- @types/jasmine@2.5.38
+-- bootstrap@4.0.0-beta
+-- chroma-js@1.3.4
+-- codelyzer@2.0.1
+-- core-js@2.5.0
+-- font-awesome@4.7.0
+-- geojson@0.4.1
+-- hammerjs@2.0.8
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@3.2.0
+-- jquery@3.2.1
+-- karma@1.4.1
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@0.2.3
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- moment@2.18.1
+-- UNMET PEER DEPENDENCY popper.js@^1.11.0
+-- protractor@5.1.2
+-- rxjs@5.4.3
+-- ts-node@2.0.0
+-- tslint@4.5.1
+-- webpack-bundle-analyzer@2.9.0
`-- zone.js@0.8.16
```

Browser:
N/A

System:
- TypeScript version: 2.4.1
- Node version: v7.8.0
- Platform:  Windows

## Angular CLI output
```
C:\Users\[Path redacted]>ng build
Date: 2017-09-06T12:06:14.031Z
Hash: fe0d48bfd0325692585c
Time: 28182ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.1 MB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 209 kB {inline} [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 54.4 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 525 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 10.8 MB [initial] [rendered]

WARNING in ./node_modules/@progress/kendo-angular-dropdowns/node_modules/@progress/kendo-angular-popup/dist/es/util.js
123:18-34 "export 'siblingContainer' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dropdowns/node_modules/@progress/kendo-angular-popup/dist/es/util.js
127:33-40 "export 'parents' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dropdowns/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
64:28-44 "export 'siblingContainer' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dropdowns/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
65:15-33 "export 'positionWithScroll' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dropdowns/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
71:15-24 "export 'addScroll' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es/util.js
123:18-34 "export 'siblingContainer' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es/util.js
127:33-40 "export 'parents' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
64:28-44 "export 'siblingContainer' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
65:15-33 "export 'positionWithScroll' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es/services/dom.service.js
71:15-24 "export 'addScroll' was not found in '@progress/kendo-popup-common'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\[Path redacted]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\[Path redacted]\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by DGolverdingen** [comment]
I can confirm this a dependency bug on @progress/kendo-popup.
My application was crashing then clicking opening the dropdownlist.
dropdowns is depending on multiple exports that don't exist in 1.2.0 of popup. 

Use this combination for the time being:
"@progress/kendo-angular-dropdowns": "1.2.0"
"@progress/kendo-angular-popup": "1.1.1",

**Comment by ggkrustev** [comment]
We introduced new feature in the Popup component which requires a newer `kendo-popup-common` package. Generally speaking the `npm install` should fetch the latest package, which didn't happened in this case.

Could you reinstall the popup packages again? Running the following command should resolve the issue:
```
//run the package.json folder
rm -rf node_modules/@progress && npm i
```

We will further tweak the `kendo-angular-popup` package to avoid this package mismatch.

**Comment by DGolverdingen** [comment]
Ok, it's working for me now.  I was using `rimraf node_modules ` and `npm install` and that did not work. But removing the @progress folder and `npm install` helped.
It still get confused of all this npm stuff going wrong.

**Comment by ggkrustev** [comment]
@simonneedham could you confirm that the given command works, like @DGolverdingen said?

**Comment by simonneedham** [comment]
@ggkrustev I'm going to be away from any dev machines for a few days. Will be able to confirm on Tuesday. Sorry.
